### ISSUE TITLE
Download Application Rejected

### ISSUE THREAD

**Issue by Liam-Xin** [scannetpp/scannetpp#102]
Hello, I would like to download the Scannet++ dataset for academic research and have submitted the signed PDF file. However, I received a notification indicating that my application was rejected. I would greatly appreciate it if you could inform me of the reasons for the rejection.

**Comment by cy94** [comment]
Hello Liam, please contact us on the email ID here and we'll help you: https://kaldir.vc.in.tum.de/scannetpp/contact
