### ISSUE TITLE
the number of frame in "pose_intrinsic_imu.json" is not the same of that from iphone videos

### ISSUE THREAD

**Issue by redolence2** [scannetpp/scannetpp#104]
Hello, thanks for your great work!

For example, scene 5a269ba6fe, in "pose_intrinsic_imu.json", the last entry is "frame_006104"; However, When I use command "python -m iphone.prepare_iphone_data iphone/configs/prepare_iphone_data.yml" to get frames from iphone video, I get frames from frame_000000.jpg to frame_006105.jpg. I wonder if the correspondence between "pose_intrinsic_imu.json" and the images is according to image name? i.e. entry "frame_006104" in "pose_intrinsic_imu.json" correspons with the image frame_006104.jpg?  If it is correct, can I simply discard the frame_006105.jpg since there is not entry "frame_006105" in json?

**Comment by cy94** [comment]
The number of frames in the video is much larger and the poses are provided only for a subset of the frames, since its not feasible to register all the iPhone frames + some failed registrations might be removed
