### ISSUE TITLE
How to render 3D semantics onto 2D iPhone images

### ISSUE THREAD

**Issue by kylekam** [scannetpp/scannetpp#105]
I was able to follow the rasterize_semantics_2d.py script to render semantics onto the DSLR images, but my goal is to get 2D semantics for the iPhone images. I tried replacing the FisheyeCamera model with the PerspectiveCamera and fed in the iPhone camera parameters but the output semantics don't align with original image. Any tips would be appreciated.

RGB Image:
![image](https://github.com/user-attachments/assets/22c02a4d-549a-4efc-aa1a-53c33ec23c87)

Rendered Semantics (the colors are wrong but the geometry is expected)
![image](https://github.com/user-attachments/assets/16fc7099-a12a-4683-b9a5-5e6a028977ce)

**Comment by cy94** [comment]
Hi @kylekam the camera pose and the RGB image seem not to match, can you double check if they have the same name?

**Comment by kylekam** [comment]
I had to add this section back.

> # apply the same transformation for fisheye cameras 
> # transpose R, then negate 1st and 2nd columns
> fisheye_R = R.mT
> fisheye_R[:, :, :2] *= -1
> # negate x and y in the transformation T
> # negate everything
> fisheye_T = -T
> # negate z back
> fisheye_T[:, -1] *= -1

![image](https://github.com/user-attachments/assets/bf16f911-182e-433b-83bb-e3d57356543c)

The segmentation masks are still kind of off but the geometry looks much more aligned now. Is there any fix for cleaning up the segmentation masks?

**Comment by cy94** [comment]
That seems ok, due to the noise in the mesh and different resolutions of the mesh vs. DSLR/iPhone, the semantics won't match the images exactly.
