### ISSUE TITLE
How can I map thousands of labels into a smaller set of 256 categories?

### ISSUE THREAD

**Issue by lif314** [scannetpp/scannetpp#106]
Hello, thank you for your awesome work! 

Just like `top100.txt` is used to prepare semantic training data and rasterize 2D semantic labels, I found that the semantic maps rendered with 100 categories are not accurate at the object edges. How can I create a `top256.txt` similar to `top100.txt` to obtain richer semantic maps?

As shown in the image below, the 2D semantic labels obtained through rasterization are not very accurate. And the white areas represent regions with an invalid label ID (-1).

![viz_DSC03437](https://github.com/user-attachments/assets/356727a3-606f-429c-a298-5f949d333b71)

**Comment by cy94** [comment]
Hi @lif314 due to noise in the mesh and the mismatch between the scan and DSLR/iPhone resolutions, these issues are expected. You can edit the `map_benchmark.csv` file to update the mapping for more classes, and then pick the top N classes as required.

**Comment by lif314** [comment]
> Hi @lif314 due to noise in the mesh and the mismatch between the scan and DSLR/iPhone resolutions, these issues are expected. You can edit the `map_benchmark.csv` file to update the mapping for more classes, and then pick the top N classes as required.

Got it, thank you for your prompt reply!
