### ISSUE TITLE
map_benchmark.csv missing classes?

### ISSUE THREAD

**Issue by ozgurcelik** [scannetpp/scannetpp#109]
Hi,
When I look at the map_benchmark.csv, I see that most of the instance_map_to cells are empty, and there are in total 31 unique non-None values there. May I ask why this is the case?

**Comment by cy94** [comment]
Hi @ozgurcelik classes without a mapping entered are used as-is
https://github.com/scannetpp/scannetpp/blob/136c416baa915738c27db1aad198429be8fba68d/semantic/prep/map_semantic.py#L50
and the rest get mapped to a different class.

**Comment by ozgurcelik** [comment]
Hi. So is there a way to map ~1.5k instances to top100?

**Comment by cy94** [comment]
The released code and mapping does that. However the mapping is not from 1.5k to 100 classes. The mapping only reduces a few classes, and then we picked the top 100 classes which have sufficient number of instances in each split to get the final top100 classes.

**Comment by ozgurcelik** [comment]
So, just to clarify take the "shoes" from top100 list. We have "shoes" and "running shoes" in instance_classes list (1.5k classes). In that case, when looking at the top100, we ignore the "running shoes" instances and only consider the original "shoes" (ones with "shoes" label in segments_anno"), as "shoes". Is that correct?
