### ISSUE TITLE
RGBD Conversion Error 

### ISSUE THREAD

**Issue by pushkalkatara** [scannetpp/scannetpp#11]
Hi Scannet++ Team,

I'm using Scannet++ videos to convert to RGB, Depth, and Mask data using the script provided [here](https://github.com/scannetpp/scannetpp#extract-rgb-frames-masks-and-depth-frames).

While running the script I got the following error:

<img width="762" alt="image" src="https://github.com/scannetpp/scannetpp/assets/21266230/056079c9-65e1-4218-af9d-b45a92b89d4a">

How do I fix this issue?

Also, is there a way to verify that the downloaded files are completely downloaded? Maybe a checksum over each file?

**Comment by cy94** [comment]
Fixed by re-downloading the file
