### ISSUE TITLE
Mesh RGB Rendering Alignment with iPhone Data

### ISSUE THREAD

**Issue by sachaMorin** [scannetpp/scannetpp#111]
Hi,

Thanks for the great dataset and the great work!

I'm interested in rendering the RGB iPhone trajectory using the scene mesh. That's already done in `common.render`, but I noticed a slight misalignment between the renderings and the original frames. I attached below an example using the first frame of c0f5742640.

The alignment is pretty good but you can see it's not exact: the kettle handle in the top right corner is a good example.

I understand the alignment between COLMAP poses and the mesh may not be perfect. I just want to double check that I'm not missing an easy way to fix this.

Thank you!
 
![render_000000](https://github.com/user-attachments/assets/23f187af-4f17-48ee-9a7e-230c8d8c7f16)
![rgb_000000](https://github.com/user-attachments/assets/d85085bb-6491-465d-81a4-4c48e2165e80)

**Comment by liu115** [comment]
Hi! Thanks a lot. Yes, this is expected. Depending on the scene, iPhone poses might have minor offsets when overlapped with the mesh. Unfortunately, we don't have an easy fix for this now. Of course, we would be happy to know if there are good tools/algorithms to fix this.

**Comment by sachaMorin** [comment]
Good to know. Thank you!
