### ISSUE TITLE
Missing data for scenes

### ISSUE THREAD

**Issue by RohanChacko** [scannetpp/scannetpp#113]
Hi, thank you for releasing this dataset. I have a few questions related to the release:

1. `nvs_test.txt` and `sem_test.txt` scene ids contain missing information as mentioned in `download_scannetpp.yml`. For example, 3D scan info is missing for `nvs_test.txt` and semantic info is missing for `sem_test.txt`. Is there a plan to release this data for these scenes?
2. Is there a timeline to release the remaining scenes in the dataset?

Thanks!

**Comment by cy94** [comment]
Hi @RohanChacko thanks for your interest.
1. That's intentional, otherwise its easy to cheat on the test set :)
2. We'll send an update to all the registered users when its ready!

**Comment by RohanChacko** [comment]
Thanks for the clarification!
