### ISSUE TITLE
frame-to-objects match

### ISSUE THREAD

**Issue by zer0o0ne** [scannetpp/scannetpp#114]
Hello! Can I match every frame with set of objects on it? I only found segments_anno.json with 3d coordinates of every object, but I need to find these objects on every frame of scene

**Comment by zer0o0ne** [comment]
Thanks for reply! I guess firstly I need to execute "prepare_training_data" script, and I don't understand "labels_path", "instance_labels_path", "mapping_file" and "list_path" in config. What should I put in these fields?

**Comment by cy94** [comment]
Hi, these are provided as part of the download. Please see the documentation https://kaldir.vc.in.tum.de/scannetpp/documentation

**Comment by cy94** [comment]
Please follow the new semantics scripts to get 2D instances
