### ISSUE TITLE
ERROR: File not found

### ISSUE THREAD

**Issue by resurgo97** [scannetpp/scannetpp#116]
```
root@cad9e7723dbc:/mnt/nas2/ksy/data_download# python download_scannetpp.py download_scannetpp.yml
ERROR: File not found: https://kaldir.vc.in.tum.de/scannetpp/download?token=[TOKEN]&file=splits/nvs_sem_train.txt
```

I typed in my token id and save directory into `download_scannetpp.yml` and ran the command, but then I observe this error and download does not proceed.

I didn't modify any other code in the yml file but for some reason I cannot download the dataset at all.

Could you help me out with this?

Thanks!

**Comment by resurgo97** [comment]
To be more specific, the issue started after I got through about 10% of the whole dataset.
Since then, I cannot download any file, even the one I had previously succeed to download.

**Comment by cy94** [comment]
Hi @resurgo97 we're currently experience some instability with our download server. Could you please try again after a few days?

**Comment by cy94** [comment]
In the first error message it seems the token hasn't been inserted, was that the last error you got? We're also experience some instability with our download server right now, it could be due to that

**Comment by resurgo97** [comment]
@cy94 Thanks for your quick reply! I did insert my actual token—I only replaced it with [TOKEN] in this post to avoid exposing it. It keeps generating the same message: `ERROR: File not found` for every file it's supposed to download. Given that you're experiencing server instability, do you know if the issue will be resolved soon?

**Comment by Aeson-Hsu** [comment]
I also encountered the same issue.

**Comment by cy94** [comment]
Please send your username/email ID to scannetpp@googlegroups.com, your token might have expired
