### ISSUE TITLE
 rasterize 3D Semantics onto 2D Images,

### ISSUE THREAD

**Issue by zlfffan** [scannetpp/scannetpp#117]
i  want to rasterize 3D Semantics onto 2D Images, but i can't find where to download the .pth file.
![屏幕截图 2024-10-19 133913](https://github.com/user-attachments/assets/b4fa464e-6065-4d33-b0d6-f6cf7d262e08)

**Comment by wuyingxiong** [comment]
I meet the same. How do you solve it？ Thanks

**Comment by cy94** [comment]
Please follow this https://github.com/scannetpp/scannetpp?tab=readme-ov-file#prepare-3d-semantics-training-data

**Comment by wuyingxiong** [comment]
Thanks！
But I still have some problems. 
In rasterize.py ，we need to load f'{image_name}.pth
```
   batch_poses = torch.Tensor(np.array(poses[batch_start_ndx:batch_start_ndx+cfg.batch_size]))
   rasterout_paths_batch = [rasterout_dir / scene_id / f'{image_name}.pth' for image_name in batch_image_list]
```
![Image](https://github.com/user-attachments/assets/16352b09-7b9f-4d58-9f79-d0ee48305f06)``
But in the previous step, unable to obtain f'{image_name}.pth'.
This is the .pth file needed for debugging and the .pth file obtained from the previous steps.

![Image](https://github.com/user-attachments/assets/1cdeffae-5260-4c6d-b143-d69233b26f0a)

![Image](https://github.com/user-attachments/assets/0d72fa32-4f7c-48b7-8197-a71ca7e3f732)

How can I solve it ？
