### ISSUE TITLE
Project page not working.

### ISSUE THREAD

**Issue by jeongyw12382** [scannetpp/scannetpp#124]
Hi. Thank you for your great effort in this work. 
I would like to download this dataset for my project, but the project page is currently down. 
Could you help resolve this issue?

**Comment by cy94** [comment]
Hi,


We are working on it, it will be back up soon :)


Best,

Chandan

________________________________
From: yoonwoojeong ***@***.***>
Sent: 28 November 2024 07:07:36
To: scannetpp/scannetpp
Cc: Subscribed
Subject: [scannetpp/scannetpp] Project page not working. (Issue #124)


Hi. Thank you for your great effort in this work.
I would like to download this dataset for my project, but the project page is currently down.
Could you help resolve this issue?
