### ISSUE TITLE
Convert iphone dataset to pinhole camera models.

### ISSUE THREAD

**Issue by ywyue** [scannetpp/scannetpp#13]
Hi team, thanks for your efforts on this great work! I found the camera model for the downloaded iPhone images is "OPENCV".
In the NVS experiments in your paper, do you convert these iPhone images to pinhole camera models? Thanks in advance!

**Comment by liu115** [comment]
No, the NVS experiments are done directly on the OPENCV camera model with distortion parameters using nerfstudio.
