### ISSUE TITLE
axis aligned mesh

### ISSUE THREAD

**Issue by BlackFox16** [scannetpp/scannetpp#25]
Hi,

I am looking for a method or a transformation matrix that can be applied to align the mesh correctly with the XYZ axes. Could you provide guidance on how to achieve this, or point me to the relevant documentation or tools within your project that could assist with this?

scan: 0a76e06478

![image](https://github.com/scannetpp/scannetpp/assets/118074019/75177fd8-f1e0-4ea7-aaa9-0a4ed5eca10e)

As it is available in Scannet:

e.g.:

scene0000_00.txt:

axisAlignment = 0.945519 0.325568 0.000000 -5.384390 -0.325568 0.945519 0.000000 -2.871780 0.000000 0.000000 1.000000 -0.064350 0.000000 0.000000 0.000000 1.000000 

axis aligned mesh:

![image](https://github.com/scannetpp/scannetpp/assets/118074019/d720ea1b-b103-4957-a4ed-2f65f2b62cc9)

I appreciate any help you can offer.

**Comment by cy94** [comment]
Hello,

We haven't provided the axis alignment code yet. We perform a rough axis alignment from the raw scan by performing PCA on the XY coordinates of the original point cloud, pick the top-1 component of this data and rotate it to match the original X axis. Then we shift the data to have all positive coordinates. For irregularly shaped (non-square) scenes the walls might not be perfectly aligned with the axes. However for simpler and square scenes the alignment should be better.
