### ISSUE TITLE
Serve on hugginface maybe?

### ISSUE THREAD

**Issue by pwais** [scannetpp/scannetpp#26]
Dear authors, thank you for making this dataset available!   I am now a couple of weeks into downloading, and your script seems to suggest it takes maybe 1-2hrs to download a single scene:

```scenes:  64%|█████████████████████████████████████████████████████████████████████▍                                      | 180/280 [126:00:46<155:49:51, 5609.92s/it]```

My guess is your servers are overloaded!  Thanks for providing the bandwidth, but maybe could there be a more efficient way to share the data?  FWIW Hugginface provides unlimited free storage, especially for research datasets.  https://huggingface.co/docs/datasets/upload_dataset   Here's an example where nerfstudio makes the mipnerf360 available https://huggingface.co/datasets/ethanweber/Mip-NeRF_360_Processed_with_Nerfstudio/tree/main  

I think hugginface also supports private datasets / custom access to protect data behind agreement / application process.  

Maybe it helps?  I will continue downloading, I hope it is not hurting your servers too much 🙊

**Comment by cy94** [comment]
Thanks for the suggestion! We will definitely work on optimizing the download and maybe rehosting it in the future :)

**Comment by pwais** [comment]
Thank you! FWIW I did finally get a 100% download and the script says "0 files missing".  Thank you so much for the dataset as well as the tool which auto-resumes and confirms integrity 👍
