### ISSUE TITLE
Error not found when download train_test_list.json

### ISSUE THREAD

**Issue by samcao0416** [scannetpp/scannetpp#3]
Hi there,

I really appreciate your work on the dataset. I applied for the dataset download and be honored to be approved. However, when I filled in the token in the yml file and ran the download code, it showed File not found: https://kaldir.vc.in.tum.de/scannetpp/download?token=MyToken(for secrecy)&file=data\56a0ec536c\dslr\train_test_lists.json. I copied the url into my browser and it showed 404 not found. Is there any mistake I made? Or this is just a bug. 

Thanks a lot!

**Comment by liu115** [comment]
It should be `data/56a0ec536c/dslr/train_test_lists.json` instead of `data\56a0ec536c\dslr\train_test_lists.json`

**Comment by samcao0416** [comment]
Thanks a lot! I use WSL instead and fix the problem

**Comment by LinLin1031** [comment]
> It should be `data/56a0ec536c/dslr/train_test_lists.json` instead of `data\56a0ec536c\dslr\train_test_lists.json`. Could be the problem of Windows treating the path.

What are the details of the specific changes made to the code?

**Comment by cy94** [comment]
Hi, yes that's right. The download script is not tested on Windows. You can
replace backward slashes with forward slashes or use WSL.

Best,
Chandan
