### ISSUE TITLE
Then `segments.json` per scene of Scannetpp

### ISSUE THREAD

**Issue by OrangeSodahub** [scannetpp/scannetpp#31]
Hi, Thanks for your share. I was wondering is there any instructions or descriptions of the `segments.json` file of each scene? BTW, where is the PTH file mentioned in preparing semantic gt?

**Comment by OrangeSodahub** [comment]
@cy94 Sorry for the missing the doc, i've checked and still want to know/double check that the `segIndinces` per scene in `segments.json` is "segment ID" aligned with the vertex extracted from mesh.ply file, so what is "segment ID"? and what the `segments` per object in `segments_anno.json` refer to? Is each number a unique indice of vertex in current scene? I'm confused.

cut of `segments.json`:
```text
{"params": {"kThresh": 0.01, "segMinVerts": 20}, "sceneId": "2022-12-15_11-18", "segIndices": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2095, 0, 0, 0, 0, 0, 2095, 2095, 0, 0, 0, 2095, 0, 0, 2095, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2095, 0, 2095, 0, 0, 0, 0, 0, 0, 2095, 0, 0, 0, 0,
```

cut of `segments_anno.json`:
```text
{"sceneId":"scannetpp.2022-12-15_11-18","appId":"stk.v1","annId":"2466","segGroups":[{"id":14,"objectId":14,"label":"wall","segments":[2506,1752,1,2,9,187,188,189,190,191,1110,1111,1269,1272,1748,1954,1956,2492,2505,2547,2189,8,192,1315,2133,4032,4375,4795,1035,468,863,1725,565,0,1128,578,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,193,194,324,325,326,327,328,329,330,333,334,335,336,337,338,340,341,342,345,348,349,350,352,353,358,359,360,363,365,366,443,444,454,455,457,460,461,472,566,567,568,575,576,577,588,590,592,861,862,881,882,883,884,885,886,887,888,987,988,989,990,994,996,997,999,1000,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1033,1036,1037,1040,1041,1042,1071,1072,1073,1123,1125,1126,1129,1407,1409,1414,1416,1417,1420,1423,1424,1425,1426,1427,1432,1433,1434,1435,1571,1605,1684,1685,1690,1692,1693,1731,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1795,1807,1861,1862,1863,2029,2138,2140,2150,2151,2155,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2247,2248,2420,2421,2422,2428,2429,2432,2457,2458,2459,2461,2462,2463,2464,2465,2466,2467,4796,4797,4798,4799,4800,4801,5458,5459,5464,5465,2571,2447,2438],"obb":{"centroid":[1.379883355255662,0.37619470675783406,1.8732113875448702],"axesLengths":[2.6524055502331114,3.529540054500103,0.6090143640806528],"normalizedAxes":[-0.998885839285373,0.047191949262094364,1.0478717729543866e-17,0,-2.220446049250313e-16,1,0.047191949262094364,0.998885839285373,2.2179721154932897e-16],"min":[0.04078789568597996,0.00944070058250912,0.10844136029481866],"max":[2.718978814825344,0.742948712933159,3.637981414794922]},"dominantNormal":[0.04719194926209437,0.9988858392853731,2.21797211549329e-16],"partId":14,"index":0}
```

**Comment by OrangeSodahub** [comment]
@cy94 I know that, but don't know what the segment ID stands for. Anyway, `segments.json` and `segments_anno.json` are the same as `xxx.segs.json` and `xxx.aggregation.json` in Scannet, respectively ?

**Comment by cy94** [comment]
There are no pth files released. The pth files are just the training data generated from the mesh and json files. You could also generate them any other way using your own code. Yes, the files are similar to the ones from ScanNet. We have not released any code for handling the bounding boxes, however those can also be used quite easily.

________________________________

**Comment by OrangeSodahub** [comment]
Thanks for your explanination. However some of my questions have not been solved, is `obb` exactly the axis-aligned bounding box? And what the `min` and `max` stand for. I found that min != centroid - axesLength / 2, max != centroid + axesLength / 2, but centroid = (min + max) / 2. So confusing.

Take the first object in the first scene as an example:
```
"obb":{
"centroid":[1.379883355255662,0.37619470675783406,1.8732113875448702],
"axesLengths":[2.6524055502331114,3.529540054500103,0.6090143640806528],
"normalizedAxes":[-0.998885839285373,0.047191949262094364,1.0478717729543866e-17,0,-2.220446049250313e-16,1,0.047191949262094364,0.998885839285373,2.2179721154932897e-16],
"min":[0.04078789568597996,0.00944070058250912,0.10844136029481866],
"max":[2.718978814825344,0.742948712933159,3.637981414794922]},
"dominantNormal":[0.04719194926209437,0.9988858392853731,2.21797211549329e-16],
"partId":14,"index":0
```
Obviously, the `axesLengths` can be calculated from `min` and `max`, but as the example shows:
`max[0] - min[0] = 2.718978814825344 - 0.04078789568597996 = 2.67819091913936404 != 2.6524055502331114 = axesLengths[0]`,
`max[1] - min[1] = 0.742948712933159 - 0.00944070058250912 = 0.73350801235064988 != 3.529540054500103 = axesLengths[1]`
`max[2] - min[2] = 3.637981414794922 - 0.10844136029481866 = 3.52954005450010334 = axesLengths[1]` ??

**Comment by OrangeSodahub** [comment]
Use the `axesLengths`:
![image](https://github.com/scannetpp/scannetpp/assets/54439582/c6a433d2-a3a2-4c1d-88b0-ab0c34ef0043)

Use the `max` - `min`:
![image](https://github.com/scannetpp/scannetpp/assets/54439582/2eecf99e-92f5-4a17-be8b-85dd716554ef)

**Comment by OrangeSodahub** [comment]
By the way, the room seems not well-axis-aligned ...

**Comment by OrangeSodahub** [comment]
cc @liu115 Hi, any instructions?

**Comment by OrangeSodahub** [comment]
@cy94 Please it's better to provide details about all kinds of keys or attributes appeared in all kinds of data files. I got stuck with understanding what do `axesLengths` `normalizedAxes` `dominantNormal` exectly mean and it is a waste of time. I thought they should be aabb (axis-aligned bounding box), without explicitly explanations someone else may waste time guessing what they are...

**Comment by Yangr116** [comment]
@cy94 @liu115 Hi, could you please explain the definitions of `centroid`, `normalizedAxes`, and `axesLengths`, as well as the coordinate system of the bounding box (e.g., does X point to the right, Z forward, and Y downward)? This would help in better utilizing your excellent dataset!

This is a visualization of the bbox, I don't know why Z-axis of bboxes is not upward as the world coordinate.

<img width="1386" alt="Image" src="https://github.com/user-attachments/assets/678522e0-fa95-487e-b40b-0c077ff1dec7" />

```python
import json
import numpy as np
import open3d as o3d
import os
from scipy.spatial.transform import Rotation
from plyfile import PlyData
import pandas as pd
import open3d as o3d


def read_plymesh(filepath):
    """Read ply file and return it as numpy array. Returns None if emtpy."""
    with open(filepath, 'rb') as f:
        plydata = PlyData.read(f)
    if plydata.elements:
        vertices = pd.DataFrame(plydata['vertex'].data).values
        faces = np.array([f[0] for f in plydata["face"].data])
        return vertices, faces

geometries = []

# Add a global coordinate frame for reference
global_coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1.0, origin=[0, 0, 0])
geometries.append(global_coordinate_frame)

ply_path = "scannnetpp-sample/mesh_aligned_0.05_semantic.ply"
point_cloud_data, _ = read_plymesh(ply_path)
semantic_all = point_cloud_data[:, -1]
unique_semantics = np.unique(semantic_all)
semantic_colors = np.random.random((len(unique_semantics), 3))
semantic_color_map = {sem: color for sem, color in zip(unique_semantics, semantic_colors)}

xyz = point_cloud_data[:, :3]
rgb = point_cloud_data[:, 3:6]
rgb_normalized = rgb / 255.0
semantic = point_cloud_data[:, -1]
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(xyz)
pcd.colors = o3d.utility.Vector3dVector(rgb_normalized)
geometries.append(pcd)

jsonfile = "scannnetpp-sample/segments_anno.json"
data = json.load(open(jsonfile))
seg_groups = data['segGroups']
obb_list = []
for idx, group in enumerate(seg_groups):
    label = group['label']
    # segments = np.array(group['segments'])
    obb_list.append(group['obb'])

for obb in obb_list:
    center = np.array(obb['centroid'])  # center in the world_coordinate
    rot = np.array(obb['normalizedAxes']).reshape(3, 3).T
    # rot = np.eye(3)
    extents = np.array(obb['axesLengths'])
    bbox = o3d.geometry.OrientedBoundingBox(center, rot, extents)  # Create OrientedBoudingBox from center, rotation R and extent in x, y and z direction
    bbox.color = [1, 0, 0]  # Set the box color to red
    box_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.3)
    box_frame.translate(center)
    box_frame.rotate(rot) 
    geometries.append(bbox)
    geometries.append(box_frame)

o3d.visualization.draw_geometries(geometries)
```
