### ISSUE TITLE
Download Error for iPhone Depth Data

### ISSUE THREAD

**Issue by Nik-V9** [scannetpp/scannetpp#32]
Hi, Thanks for your amazing effort with this dataset!

I've been downloading the data. However, I keep encountering the following error when downloading multiple scans (for example, scene `b20a261fdf`. I wanted to flag it so that it can be fixed.

```
Traceback (most recent call last):
  File "download_scannetpp.py", line 191, in <module>
    main(args)
  File "download_scannetpp.py", line 181, in main
    if not check_download_file(cfg, src_path, tgt_path):
  File "download_scannetpp.py", line 67, in check_download_file
    return download_file(url, local_path, verbose=verbose, make_parent=True)
  File "download_scannetpp.py", line 50, in download_file
    urlretrieve(url, filename)
  File "/usr/lib/python3.8/urllib/request.py", line 286, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 239697920 out of 464026680 bytes>
```

**Comment by liu115** [comment]
Hi! This might because the socket is terminated in the middle of downloading so the file is incomplete, especially for large files 
like iphone RGB and depth, which could be hundreds MB. We couldn't reproduce this issue under our system and network environment, but maybe it's because the system has shorter default socket timeout or if a VPN is used. 
https://stackoverflow.com/questions/68161646/why-error-urllib-error-contenttooshorterror

One easy solution is to replace `urlretrieve(...)` with `os.system(f"wget -O {filename} {url}")`. Would love to know if there is a better solution.

**Comment by Nik-V9** [comment]
Thanks for the response! Interestingly, if I replace the `urlretrieve` with a `wget`, I'm getting a file not found error:

`ERROR: File not found: https://kaldir.vc.in.tum.de/scannetpp/download?token=<API Token>&file=data/be0ed6b33c/dslr/train_test_lists.json`

**Comment by liu115** [comment]
Checked on our side that the file is not missing. Could you try opening the link in your browser? If still not working, you could send your personal information to the our contact email (in the website).

or maybe you simply need to add `\"` around the url.
```python
os.system(f"wget -O {filename} \"{url}\"")
```

**Comment by Svithjod** [comment]
Yes I believe the '&' token in the url string is causing File Not Found problem. Adding `\"` works for me.

**Comment by cy94** [comment]
we made some improvements to the download server, please reopen if you still have this issue

**Comment by crepejung00** [comment]
Hi,
I have encountered the same issue and changed the code to os.system(f"wget -O {filename} \"{url}\"") as written in the comment. However, this time the wget failed with the error shown below. Should I just try again?

```
--2025-01-05 23:02:54--  (try:20)  https://kaldir.vc.in.tum.de/scannetpp/download/v2?token=Jtn3wqt69bB7R9RxE2fDnX1q7pzYRdJyF0qDMbWifPRJ1ptHljEQlJmNY9tmURiX&file=data/b08a908f0f/dslr/colmap.zip
Connecting to kaldir.vc.in.tum.de (kaldir.vc.in.tum.de)|131.159.98.128|:443... connected.
HTTP request sent, awaiting response... 206 PARTIAL CONTENT
Length: 129293001 (123M), 60301443 (58M) remaining [application/zip]
Saving to: ‘/mnt/sdb/data/data/b08a908f0f/dslr/colmap.zip’

/mnt/sdb/data/data/b08a908f0f/dslr/colmap  53%[+++++++++++++++++++++++++++++++++++++++++++++                                        ]  65.79M  --.-KB/s    in 0s      

2025-01-05 23:02:55 (0.00 B/s) - Connection closed at byte 68991558. Giving up.

scenes:  18%|████████████████████████████████████████████▌                                                                                                                                                                                                               | 178/1006 [11:53:23<55:18:30, 240.47s/it]                           
Traceback (most recent call last):
  File "/mnt/sdb/data/data_download/download_scannetpp.py", line 213, in <module>
    main(args)
  File "/mnt/sdb/data/data_download/download_scannetpp.py", line 190, in main
    with zipfile.ZipFile(tgt_download_path, 'r') as zip_ref:
  File "/home/cvlab03/anaconda3/envs/scannet/lib/python3.10/zipfile.py", line 1272, in __init__
    self._RealGetContents()
  File "/home/cvlab03/anaconda3/envs/scannet/lib/python3.10/zipfile.py", line 1339, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by crepejung00** [comment]
Sorry for posting the token, I was not aware that the token was shown in the command line.
Actually, due to the large size of the data I was downloading the dataset to the server that is required to connect with a VPN. Are there any other ways that I can pass this specific data? 
Should I download this specific file with a connection that does not require VPN?

**Comment by cy94** [comment]
Yes, please try without a VPN
