### ISSUE TITLE
Multilabel for vertex

### ISSUE THREAD

**Issue by OrangeSodahub** [scannetpp/scannetpp#39]
Hi, this is the scene0a7cc12c0e, I calculated labels for each point however I only want a subset of classes, e.g., exclude the `jackets`, and `carpet`, when I filtered out them, there will be holes (like the areas of two red boxes). I want know if these vertices have multiple labels? e.g., for the segments of jackets, could also be considered as the `bed`.
![image (5)](https://github.com/scannetpp/scannetpp/assets/54439582/7ffecf72-1312-47f1-b681-ba53ed3d42ab)

![image](https://github.com/scannetpp/scannetpp/assets/54439582/b7117584-c4af-4b26-8625-cb94b0cebc1d)
The balck items: `pillow` and `blanket`, do they have another label `bed`?

**Comment by cy94** [comment]
Hi, there could be some vertices in scans that have no labels at all. Its not clear what is visualized in the 1st image. If you visualize only points that have labels, then there will be holes. Reg. the 2nd image, its not clear again what exactly is visualized. The full set of annotations is in the JSON file. There you can check which vertices have/don't have annotations.

**Comment by OrangeSodahub** [comment]
@cy94 Sorry for the unclearness, as I said, I calculate the labels for each verts according to JSON file. And what I emphasized two areas (red boxes) are a bed, and part of the floor, these two holes should be classes `blanket` on the bed, and `carpet` on the floor,   which is shown in black in 2nd fig. So I want to know do these items have multiple labels? For example, the blanket on the bed, could be labeled as blanket itself, and also bed, the carpet on the floor, could be labeled as carpet, and also floor. If so, in this case, I could ignore the classes blanket and carpet, in the meantime these are no holes in bed and floor.

**Comment by cy94** [comment]
It depends on how you are getting the labels onto the vertices. If you just apply every instance from the JSON onto the corresponding vertices, then you should get atleast 1 label on the vertices. If you want to get multilabels you can use your own code, or using the provided data preparation code with multilabel set to True. If there is no label on some vertex in either case that means its not annotated, or it doesnt belong to the set of labels which you have picked

**Comment by OrangeSodahub** [comment]
@cy94 Thanks for you explanation. But I still have questions. What I want to know is a specific example of multilabel, or for the cases I picked, maybe you are not sure if there exist multilabel for mya cases. 

Well, I checked the `segments` of label `blanket`, and they are unique in `segment_anno.json`, no other any object has the same segments as the `blanket`, so does that means those labels are unique?

**Comment by cy94** [comment]
Sorry its not clear to me again. Are you trying to find a specific case of multilabel? Then the best way is to use all the labels, prepare the PTH data using the multilabel option, and then check for vertices that have more than 1 label. 

In your case it looks like that part has no labels, which could mean -
- that part is not annotated
- it has a label thats not part of the label set that you are visualizing

**Comment by cy94** [comment]
I just checked the annotation for that scene, its originally blanket and pillow. Both of these are in the benchmark class list.

**Comment by OrangeSodahub** [comment]
@cy94 Sorry for my unclear description. As I said, I only use a subset of classes, which excludes the pillow and blanket, once I filter out them then the `bed` will have a big hole, so I'm searching their multilabel.

**Comment by OrangeSodahub** [comment]
So could you provide an example, in which case a vertex could have multilabel? A jacket on a table? It's inconvenient for me to run your script and check them in person.

**Comment by cy94** [comment]
Jacket on chair, books inside a bookshelf, bed+blanket, window as part of a door are the common ones I've seen. The PTH data preparation should only take about 30 minutes for the whole train set so you can use that to analyze the annotations.

**Comment by OrangeSodahub** [comment]
So why here in my case the blanket on the bed has no multilabel, I will check then

**Comment by cy94** [comment]
Not every bed/blanket combination is multilabeled in exactly the same way. Some of them might have only single labels.
