### ISSUE TITLE
5 files missing

### ISSUE THREAD

**Issue by DianCh** [scannetpp/scannetpp#4]
Hi, I got 5 files missing after the download finishes:

```
5 files missing: [PosixPath('/home/ubuntu/scannetpp/data/f9f95681fd/dslr/resized_images/DSC08914.JPG'), PosixPath('/home/ubuntu/scannetpp/data/13c3e046d7/dslr/resized_images/DSC01602.JPG'), PosixPath('/home/ubuntu/scannetpp/data/13c3e046d7/dslr/resized_images/DSC01603.JPG'), PosixPath('/home/ubuntu/scannetpp/data/e7af285f7d/dslr/resized_anon_masks/DSC03122.png'), PosixPath('/home/ubuntu/scannetpp/data/a980334473/dslr/resized_images/DSC04004.JPG')]
```

and re-downloading doesn't help me get them - I got these exact same missing files each time. May I ask how to download these files? Thank you!

**Comment by liu115** [comment]
Could you try accessing the data in your browser? I checked that those files exist and can be accessed in the browser as well. For example,
```
https://kaldir.vc.in.tum.de/scannetpp/download?token=YOUR_TOKEN&file=data/f9f95681fd/dslr/resized_images/DSC08914.JPG
```

**Comment by DianCh** [comment]
@liu115 I got 404 Not Found error with my token in the link.
<img width="810" alt="Screenshot 2023-10-16 at 1 54 48 PM" src="https://github.com/scannetpp/scannetpp/assets/32043460/e357a8ed-6a2b-4f0f-abc0-45748ca4a3e8">

**Comment by liu115** [comment]
Could you send your token and you user email to [ScanNet++ team](mailto:scannetpp@googlegroups.com)?

**Comment by DianCh** [comment]
Sounds good, just did. Thank you for helping!

**Comment by DianCh** [comment]
I wrote to 

scannetpp@googlegroups.com

but seem to get "group non-exist" - Am I writing to the right email?
<img width="698" alt="Screenshot 2023-10-16 at 2 14 10 PM" src="https://github.com/scannetpp/scannetpp/assets/32043460/338b1098-7b3e-439b-bdcc-917cb89e4576">

**Comment by liu115** [comment]
We found the problem. Could you try sending the email again?

**Comment by DianCh** [comment]
Just did, thanks!
