### ISSUE TITLE
question regarding segments.json

### ISSUE THREAD

**Issue by ywyue** [scannetpp/scannetpp#48]
Hi ScanNet++ team, thanks for your great work! I downloaded the latest data using the latest downloading script. However, when I am checking `segments.json`, e.g. for scene 56a0ec536c, the `segments['segIndices']` have a length of 1077300 and look like this: 
`[0, 1, 2, 3, 4, 5, ..., 1077297, 1077298, 1077299]`. In other words, it seems that they are just incremental from 0 to maximum length with step 1. Other scenes also have this pattern. I wonder is this expected or a bug? Thanks in advance.

**Comment by cy94** [comment]
Yes that's right, the annotation is provided on the vertices

**Comment by ZheningHuang** [comment]
Dear Scannet++ team,

Thanks again for the great work.

I have a nuanced question to ask here.

I understand that the current `segments.json` only provides segment IDs incrementally for each point, meaning that the segment information used during labeling process is not revealed, which is unlike the ScanNet dataset.

However, I noticed in a previous question on Nov 2023, where `segments.json` was quoted, and it seems there are actually some segment IDs. Just curious, has this been removed in the newer version of ScanNet++, or can it be found somewhere else?

https://github.com/scannetpp/scannetpp/issues/31:

> @cy94 Sorry for the missing the doc, i've checked and still want to know/double check that the `segIndinces` per scene in `segments.json` is "segment ID" aligned with the vertex extracted from mesh.ply file, so what is "segment ID"? and what the `segments` per object in `segments_anno.json` refer to? Is each number a unique indice of vertex in current scene? I'm confused.
> 
> cut of `segments.json`:
> 
> ```
> {"params": {"kThresh": 0.01, "segMinVerts": 20}, "sceneId": "2022-12-15_11-18", "segIndices": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2095, 0, 0, 0, 0, 0, 2095, 2095, 0, 0, 0, 2095, 0, 0, 2095, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2095, 0, 2095, 0, 0, 0, 0, 0, 0, 2095, 0, 0, 0, 0,
> ```
> 
> cut of `segments_anno.json`:
> 
> ```
> {"sceneId":"scannetpp.2022-12-15_11-18","appId":"stk.v1","annId":"2466","segGroups":[{"id":14,"objectId":14,"label":"wall","segments":[2506,1752,1,2,9,187,188,189,190,191,1110,1111,1269,1272,1748,1954,1956,2492,2505,2547,2189,8,192,1315,2133,4032,4375,4795,1035,468,863,1725,565,0,1128,578,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,193,194,324,325,326,327,328,329,330,333,334,335,336,337,338,340,341,342,345,348,349,350,352,353,358,359,360,363,365,366,443,444,454,455,457,460,461,472,566,567,568,575,576,577,588,590,592,861,862,881,882,883,884,885,886,887,888,987,988,989,990,994,996,997,999,1000,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1033,1036,1037,1040,1041,1042,1071,1072,1073,1123,1125,1126,1129,1407,1409,1414,1416,1417,1420,1423,1424,1425,1426,1427,1432,1433,1434,1435,1571,1605,1684,1685,1690,1692,1693,1731,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1795,1807,1861,1862,1863,2029,2138,2140,2150,2151,2155,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2247,2248,2420,2421,2422,2428,2429,2432,2457,2458,2459,2461,2462,2463,2464,2465,2466,2467,4796,4797,4798,4799,4800,4801,5458,5459,5464,5465,2571,2447,2438],"obb":{"centroid":[1.379883355255662,0.37619470675783406,1.8732113875448702],"axesLengths":[2.6524055502331114,3.529540054500103,0.6090143640806528],"normalizedAxes":[-0.998885839285373,0.047191949262094364,1.0478717729543866e-17,0,-2.220446049250313e-16,1,0.047191949262094364,0.998885839285373,2.2179721154932897e-16],"min":[0.04078789568597996,0.00944070058250912,0.10844136029481866],"max":[2.718978814825344,0.742948712933159,3.637981414794922]},"dominantNormal":[0.04719194926209437,0.9988858392853731,2.21797211549329e-16],"partId":14,"index":0}
> ```



Thanks a lot for your help.
