### ISSUE TITLE
Problem related to extracting mask frames from iPhone

### ISSUE THREAD

**Issue by DaLi-Jack** [scannetpp/scannetpp#49]
Hi, thanks for your great work! 
I extracted mask frames from an iPhone video following your [instructions](https://github.com/scannetpp/scannetpp?tab=readme-ov-file#extract-rgb-frames-masks-and-depth-frames), but I noticed that all the mask values are 255. 
Could you please advise on where I might have made a mistake? 
I would greatly appreciate any assistance you can offer!

**Comment by DaLi-Jack** [comment]
And I encountered a bug while extracting depth frames
![image](https://github.com/scannetpp/scannetpp/assets/70205757/144d79a7-cacf-45ef-816b-78a94ef2541e)

**Comment by cy94** [comment]
Could you try downloading that file again? It also says insufficient space, could you check if there is enough RAM / space on your disk?

________________________________

**Comment by DaLi-Jack** [comment]
yes! I found that the problem "extracting depth frames" was related to the RAM space. Thank for your reply!
But for the first question, why all the mask values are 255?

**Comment by DaLi-Jack** [comment]
Sorry, I didn't read the document carefully. I found that the mask here is not a semantic label, but an indication of whether the pixel is valid. (0: invalid, 255: valid pixels).
![image](https://github.com/scannetpp/scannetpp/assets/70205757/c4c4d583-0337-42fc-9809-5dfdd5116fc6)
Thank you again for your great work!
