### ISSUE TITLE
Pink-colored regions on input mesh

### ISSUE THREAD

**Issue by star9988rr** [scannetpp/scannetpp#5]
Hi, thank you for your great work!

I have noticed that some of the input meshes are displaying unexpected pink-colored regions. For instance, I have attached a screenshot of the scene "5ee7c22ba0." Is there a mistake that I made, or is the original point cloud supposed to look like this?

Thank you very much!
<img width="1173" alt="截屏2023-10-17 下午4 30 00" src="https://github.com/scannetpp/scannetpp/assets/30023086/2a6a1a3e-8435-4a39-858c-e44f937e0b19">

**Comment by cy94** [comment]
Please refer to the documentation https://kaldir.vc.in.tum.de/scannetpp/documentation

**Comment by DianCh** [comment]
Hi @star9988rr ! Would you mind telling me what visualization tool you are using here? Thanks!

**Comment by star9988rr** [comment]
I use MeshLab to visualize it :)
