### ISSUE TITLE
Why do the camera extrinsics differ between the dslr/colmap/images.txt and nerfstudio/transforms.json? 

### ISSUE THREAD

**Issue by DaLi-Jack** [scannetpp/scannetpp#50]
Hi, thanks for your great work!
I found the camera extrinsic in dslr/colmap/images.txt for every image was different from camera extrinsic in nerfstudio/transforms.json.
as the below screenshot:
I discovered that the camera extrinsic in the dslr/colmap/images.txt for each image differs from those in the nerfstudio/transforms.json, as shown in the screenshot below:
![1](https://github.com/scannetpp/scannetpp/assets/70205757/82369a9c-4ed1-4f37-b64c-eea390d31429)
For rendering color and depth images from a 3D mesh, using the camera extrinsic from dslr/colmap/images.txt, as per your [instructions](https://github.com/scannetpp/scannetpp?tab=readme-ov-file#render-depth-for-dslr-and-iphone), is correct. However, using the camera extrinsics from nerfstudio/transforms.json results in all rendered images being blank.
Could you please advise on where I might have made a mistake?
Are these two camera extrinsics the same coordinate system?

**Comment by liu115** [comment]
The camera extrinsic in nerfstudio/transforms.json follow the nerfstudio format (OpenGL convention) as mentioned in the document. Please refer to [nerfstudio](https://docs.nerf.studio/quickstart/data_conventions.html) for more details. They are not the same as the colmap format. For example, one use -z for the camera direction while the other use +z.

**Comment by DaLi-Jack** [comment]
I see! Thank you for your answer.
