### ISSUE TITLE
principle point after undistortion

### ISSUE THREAD

**Issue by bmmi7** [scannetpp/scannetpp#51]
Hi there, thanks for your wonderful work!

Why do you manually set the principle point to the center of the image after fisheye undistortion?https://github.com/scannetpp/scannetpp/blob/592a19ee9de2a4c7349dd6e27882ea4283203114/dslr/undistort.py#L27

Also is it possible to make opencv and colmap undistortion consistent? currently "the result here is different from the ones generated by OpenCV".

**Comment by liu115** [comment]
The reason to set principle to the center after undistortion is mainly to make the data more approachable to existing methods that have this assumption (such as gaussian splatting).

Using the opencv undistortion script is recommended. Our NVS benchmark undistortion track is based on this. Colmap undistortion has less control, so it's hard to make the two consistent. We might consider to remove it later.
