### ISSUE TITLE
Visualising Semantic Training Data - Colour Palette

### ISSUE THREAD

**Issue by geanrobotics** [scannetpp/scannetpp#53]
Hello, I am trying to visualise the semantic training data using this script `python -m semantic.viz.viz_pth_data semantic/configs/viz_pth_data.yml`, please can you tell me where I can find the palette colour text file for the `palette_path` variable to match the semantic colours used for the ground truth? Thank you in advance.

**Comment by Antoine251** [comment]
Same question here ! ;)

**Comment by cy94** [comment]
[scannet200.txt](https://github.com/scannetpp/scannetpp/files/14585551/scannet200.txt)
Could you try with this? We cycle through this set of 200 colors by doing `semantic_index % 200`
