### ISSUE TITLE
Question about "mesh_aligned_0.05_mask.txt".

### ISSUE THREAD

**Issue by LinLin1031** [scannetpp/scannetpp#55]
I downloaded the mesh and point clouds for all scenes, but found that all the "mesh_aligned_0.05_mask.txt" are empty files, is this normal? @cy94 
![image](https://github.com/scannetpp/scannetpp/assets/50825626/040f1897-f50c-4dff-b798-01e179f94df0)

**Comment by cy94** [comment]
Yes thats fine, that means there are no vertices anonymized in the mesh.
