### ISSUE TITLE
Difference between pc_aligned.ply and the sampled_points

### ISSUE THREAD

**Issue by sczhou21** [scannetpp/scannetpp#57]
Excuse me, I just begin to do some research about 3D segmentation recently so that I have some questions about the dataset. In the downloaded files, every scene consists of a "pc_aligned.ply" file. In addition, according to the code, we need to run "python -m semantic.prep.prepare_training_data semantic/configs/prepare_training_data.yml" to sample the point clouds from the meshes. I don't know what's the difference between these two point clouds?

**Comment by cy94** [comment]
Please refer to the documentation https://kaldir.vc.in.tum.de/scannetpp/documentation
and this section https://github.com/scannetpp/scannetpp?tab=readme-ov-file#prepare-3d-semantics-training-data
