### ISSUE TITLE
AxisAlignment Matrix

### ISSUE THREAD

**Issue by sczhou21** [scannetpp/scannetpp#58]
Excuse me, can you provide the AxisAlignment matrix as in Scannet? I want to do some research on domain generalization from Scannet to Scannet++. But the point cloud of Scannet++ now is not aligned with the axis as mentioned in #25.  Therefore, there will be a large domain gap. I would appreciate it if you could offer any assistance.

**Comment by cy94** [comment]
Hi, the scenes are already automatically aligned in the 1st quadrant as described here https://github.com/scannetpp/scannetpp/issues/25#issuecomment-1800035019
If you need a perfect alignment then it has to be done manually

**Comment by sczhou21** [comment]
Thank you very much. Could you further give some advice on how to do perfect alignment manually without the AxisAlignment matrix?

**Comment by cy94** [comment]
I think its this, can you try it out? https://github.com/ScanNet/ScanNet/tree/master/Alignment

**Comment by sczhou21** [comment]
Thanks very much. I'll try it later.
