### ISSUE TITLE
How do you align the colmap poses and pointclouds with the 3D scans

### ISSUE THREAD

**Issue by zubair-irshad** [scannetpp/scannetpp#59]
Great work! Could you share more details and potentially some code on how did you align the colmap poses and point clouds with the 3D scans?

Thanks!

**Comment by cy94** [comment]
Hi, please see section 3.4 here https://arxiv.org/pdf/2308.11417.pdf for some details. We will try to release code as well. Let us know if we can help with any specific details before that
