### ISSUE TITLE
Download dataset error

### ISSUE THREAD

**Issue by 520jz** [scannetpp/scannetpp#6]
Hi appreciate to your awesome work!
I have passed the application and obtained the download script, but there seems to be something wrong with this script
![image](https://github.com/scannetpp/scannetpp/assets/125104736/668cf1d2-a7db-446e-b747-ae496ed0132c)
How to solve this problem

**Comment by liu115** [comment]
It's because Windows use the backslash. Please refer to #3.

**Comment by 520jz** [comment]
Thank you very much！
________________________________
发件人: ***@***.*** ***@***.***> 代表 Yueh-Cheng Liu ⒃莱 ***@***.***>
发送时间: 2023年10月19日 04:55
收件人: scannetpp/scannetpp ***@***.***>
抄送: jzyu ***@***.***>; Author ***@***.***>
主题: Re: [scannetpp/scannetpp] Download dataset error (Issue #6)


It's because Windows use the backslash. Please refer to #3<https://github.com/scannetpp/scannetpp/issues/3>.

―
