### ISSUE TITLE
Undistort 2D depth and semantic

### ISSUE THREAD

**Issue by tberriel** [scannetpp/scannetpp#65]
Hi, first of all thanks for your great work!
I am trying to generate 2D segmentation labels for dslr images. 
I followed #7  to render them, nevertheless all rendered images (including RGB, depth and semantic labels) are distorted.
Is there a way to directly render them without distortion? If not, how could I undistort them?
Thanks in advance for your help :D

**Comment by ShuhongLL** [comment]
My solution is,

After rendering the depth and color images, you will get two folders:
`render_color` and `render_depth` with distorted RGB images and depth map

Then you can call `dslr.undistorted` to undistort them, similar to example in README, but with some changes in `dslr/undistort.py`.
In `undistort_frames()`, add the following code in the loop (etc. line 62) to handle depth map:

```
file_name = frame["file_path"].replace('.JPG', '.png') # Depth map is png format
depth_path = Path(input_depth_dir) / file_name
depth = cv2.imread(str(depth_path), cv2.IMREAD_UNCHANGED)
undistorted_depth = cv2.remap(
    depth,
    map1,
    map2,
    interpolation=cv2.INTER_NEAREST, # Use nearest neighbor interpolation
    borderMode=cv2.BORDER_CONSTANT,
    borderValue=20.0 # Assuming 20.0 is an appropriate border value for missing depth information
)
out_depth_path = Path(out_depth_dir) / file_name
out_depth_path.parent.mkdir(parents=True, exist_ok=True)
cv2.imwrite(str(out_depth_path), undistorted_depth)
```

define  `input_depth_dir` and `out_depth_dir` respectively.

I have tested it and this works for me.

**Comment by tberriel** [comment]
Thanks for sharing your solution! 
Regarding borderMode, is there any particular reason you chose BORDER_CONSTANT rather than BORDER_REFLECT_101 which would mimic the rgb mapping?

**Comment by ShuhongLL** [comment]
I am considering `BORDER_REFLECT_101` more suitable for RGB images; however for depth, especially when the mesh apparently contains holes, specifying a constant depth value for missing pixels might be more approperiate here. Mirror the border pixels won't help (depth presents spatial information about a scene which needs to be accurate), and it might also produce artifects. The choice is up to your usecase.

**Comment by tberriel** [comment]
I see your point. Thanks for your help!

**Comment by zhongyingji** [comment]
Hi, after getting the 'vert_indices' of each pixel in the 2D map, how to get the semantic label? Thank you: )

**Comment by tberriel** [comment]
For each scene you have to load the file "mesh_aligned_0.05_semantic.ply", and then for each image use vert_indices to index the loaded file and retrieve a label for each vertex. For each pixel you have to choose the label either randomly sampling one of the three associated vertices or by majority vote. Finally, you will have to undistort semantic labels using the script previously mentioned in this thread.
 An example of the code modifications in render.py could be
```
...
import scipy.stats
from plyfile import PlyData

def main(args):
    ...
    # load vertices semantic labels
    plydata = PlyData.read(str(scene.scan_sem_mesh_path))
    semantic_mesh = plydata.elements[0]['label']
    for device in render_devices:
        ...
        semantic_dir = Path(cfg.output_dir) / scene_id / device / "render_semantic"
        semantic_dir.mkdir(parents=True, exist_ok=True)
        for image_id, image in ...
           ...
           rgb, depth, vert_indices = render_engine.renderAll(world_to_camera, near, far)
           ...
           # Select vertices' semantic labels using majority vote
           vert_labels = np.where(vert_indices>0, semantic_mesh[vert_indices], -100) # Unlabeled vertices have value -100
           semantic = scipy.stats.mode(vert_labels, axis=-1).mode 
           #semantic = vert_labels[...,0] # Mode is quite time expensive, to be faster you can just select the first, although you will lose accuracy
           # save semantic labels as png to undistort using the same script than for depth
           semantic = np.where(semantic>=0, semantic, 65535).astype(np.uint16) 
           imageio.imwrite(semantic_dir / depth_name, semantic)
           
```

**Comment by zhongyingji** [comment]
I got it. Thank you for your help : )
