### ISSUE TITLE
Generating Superpoint aligning with the sampled pointcloud

### ISSUE THREAD

**Issue by PhucNDA** [scannetpp/scannetpp#66]
Hi, the current version doesn't support aligning the superpoint from Graph-based Segmentation with the sampled point cloud. While Superpoint is crucial in training the Semantic/Instance segmentation. Could you provide the aligning script ?

Thank you for the hard work on processing the dataset!

**Comment by PhucNDA** [comment]
Also, when dealing with sampled points, we currently cannot get 2D-3D mapping by rasterizing the semantic label via camera pose.

**Comment by RayYoh** [comment]
> Hi, the current version doesn't support aligning the superpoint from Graph-based Segmentation with the sampled point cloud. While Superpoint is crucial in training the Semantic/Instance segmentation. Could you provide the aligning script ?
> 
> Thank you for the hard work on processing the dataset!

Have similar confusion. Does it work if use the [this ](https://github.com/Karbo123/segmentator) code

**Comment by cy94** [comment]
You should be able to use any segmentation / superpoint algorithm to segment the mesh.  We don't provide the mesh segments in the dataset
