### ISSUE TITLE
How to get the 2D segmentation annotation

### ISSUE THREAD

**Issue by gbliao** [scannetpp/scannetpp#7]
Hi, thanks for your great work.  Could you tell me how to get the 2D segmentation annotation of each image? It will help me a lot.

**Comment by cy94** [comment]
Hi, you can rasterize the mesh onto the 2d images yourself or you can refer to the code for rendering depth. We will release code for rendering semantics as well soon.

**Comment by cy94** [comment]
Code is in our official repo: https://github.com/scannetpp/scannetpp

**Comment by DianCh** [comment]
I've added the following lines to `render.h`:

```
    typedef std::tuple<py::array_t<uint8_t>, py::array_t<float>, py::array_t<int>, py::array_t<int>> RenderOut;
    // ...
    // ...
    // ...
        py::array_t<int> semantic_array(
            py::buffer_info(
                render_semantic.data,
                sizeof(int), //itemsize
                py::format_descriptor<int>::format(),
                2, // ndim
                std::vector<size_t> {render_semantic.rows, render_semantic.cols}, // shape
                std::vector<size_t> {sizeof(int) * render_semantic.cols, sizeof(int)} // strides
            )
        );
        return std::make_tuple(
            std::move(rgb_array),
            std::move(depth_array),
            std::move(vert_indices_array),
            std::move(semantic_array)
        );
```

And the returned semantic array has all zero entries; what else do I need to modify?

**Comment by liu115** [comment]
Hi if you want to do rasterization to get the 2D-3D mapping, the simplest way is by calling the [renderpy](https://github.com/liu115/renderpy) package. You could refer to the [depth rendering code](https://github.com/scannetpp/scannetpp/blob/ff464796128b63336662e12cca59b250500bf8f4/common/render.py#L75) in the repo.
```
rgb, depth, vert_indices = render_engine.renderAll(world_to_camera, near, far)
```
the `vert_indeices` here is the 2D-3D correspondence map. Each pixel has three values: the global index of the three vertexes of the first intersecting triangle in the z-buffer. You could use this information to map 3D semantic annotations to 2D.

**Comment by DianCh** [comment]
@liu115 Thanks for the reply! Yes I was trying to modify `render.h` in renderpy, mocking what's done with depth. I added lines mentioned above, re-compiled the renderpy tool, and received numpy semantic array - however the arrays contains all zeros. Can you please let me know if the modification I made is right?

**Comment by liu115** [comment]
That's not what I mean. Modifying `render.h` to achieve your goal can be done but it's more complicated and requires some knowledge about OpenGL.

I would recommend you just use the python interface that is already provided [(example)](https://github.com/liu115/renderpy#usage)
```rgb, depth, vert_indices = render_engine.renderAll(world_to_camera, near, far)```
and directly use the `vert_indices` to get the 2D semantic labels as I mentioned in the previous comment.

**Comment by DianCh** [comment]
@liu115 Ah I see, thank you! Is it possible that the three vertices of a triangle belong to different instances? If that happens, does it make sense to take the majority vote from the three to decide the instance id of that pixel?

**Comment by liu115** [comment]
Yes, there is a small chance that it would happen (on the boundary of an object for example). I believe majority vote or even randomly assign should be fine.

**Comment by gbliao** [comment]
@cy94 @liu115 @DianCh Hi, may I ask how to query the 2D semantic labels for each vert_indices?

**Comment by gbliao** [comment]
Hi, when I use the semantic of vert_indice to get the 2D semantic labels, however, I get the following very strange results. 

The left side is rgb and the right side is semantic. 

![vis](https://github.com/scannetpp/scannetpp/assets/87977851/bee27cae-f43f-48e0-8b58-4a60e68ce586)

**Comment by zhongyingji** [comment]
Hi, based on the renderer, I can get the vert_indices of each pixel. But how to get the semantic labels? 

> That's not what I mean. Modifying `render.h` to achieve your goal can be done but it's more complicated and requires some knowledge about OpenGL.
> 
> I would recommend you just use the python interface that is already provided [(example)](https://github.com/liu115/renderpy#usage) `rgb, depth, vert_indices = render_engine.renderAll(world_to_camera, near, far)` and directly use the `vert_indices` to get the 2D semantic labels as I mentioned in the previous comment.

**Comment by zhongyingji** [comment]
I noticed that in 
https://github.com/liu115/renderpy/blob/97d337d85fce12dbe6377026aa8fcfb8ef2f9abe/src/render.h#L138

The engine also returns the semantic. Is it usable?
