### ISSUE TITLE
Train and Val split for 3D semantic/instance segmentation

### ISSUE THREAD

**Issue by RayYoh** [scannetpp/scannetpp#71]
Hi authors,
After running `python -m semantic.prep.prepare_training_data semantic/configs/prepare_training_data.yml`, I find that just 280 `.pth` files are generated. But for 50 testing scenes, how can I get their pth files?

And also, is there official split file for the train and val sets?

In addition, when running `python -m semantic.viz.viz_pth_data semantic/configs/viz_pth_data.yml`, I cannot find the palette file.

**Comment by cy94** [comment]
Hi, the split files are downloaded along with the data, it should be in the "splits" directory. The same script can be used to prepare `pth` files for the test set, and not use the transforms for adding labels, or you can sample points on the mesh yourself with our code as reference. For the palette you can use any random colors, eg `

semantic_colors = np.random.randint(0, 255, (len(semantic_labels), 3))`
. We will add it for download soon.

________________________________
From: RayYoh ***@***.***>
Sent: 13 March 2024 05:22:52
To: scannetpp/scannetpp
Cc: Subscribed
Subject: [scannetpp/scannetpp] Train and Val split for 3D semantic/instance segmentation (Issue #71)


Hi authors,
After running python -m semantic.prep.prepare_training_data semantic/configs/prepare_training_data.yml, I find that just 280 .pth files are generated. But for 50 testing scenes, how can I get their pth files?

And also, is there official split file for the train and val sets?

In addition, when running python -m semantic.viz.viz_pth_data semantic/configs/viz_pth_data.yml, I cannot find the palette file.

**Comment by cy94** [comment]
Hi, the split files are downloaded along with the data, it should be in the "splits" directory. The same script can be used to prepare `pth` files for the test set, and not use the transforms for adding labels, or you can sample points on the mesh yourself with our code as reference. For the palette you can use any random colors, eg 

`semantic_colors = np.random.randint(0, 255, (len(semantic_labels), 3))`

. We will add the colors used by us for download soon.

**Comment by cy94** [comment]
Specifically you have to remove the transforms `get_labels_on_vertices` and `map_label_to_index` for the test set because labels are not provided. Could you try this out?

**Comment by RayYoh** [comment]
> Hi, the split files are downloaded along with the data, it should be in the "splits" directory. The same script can be used to prepare `pth` files for the test set, and not use the transforms for adding labels, or you can sample points on the mesh yourself with our code as reference. For the palette you can use any random colors, eg
> 
> `semantic_colors = np.random.randint(0, 255, (len(semantic_labels), 3))`
> 
> . We will add the colors used by us for download soon.

Hi, thanks for your reply. When I run the code, I comment this line [here](https://github.com/scannetpp/scannetpp/blob/34a10a66503c77cb924db4ef618993d6ffe0d9c0/semantic/prep/prepare_training_data.py#L28), because I have no complete scene list in my `split` folder. I just have `nvs_sem_train.txt  nvs_sem_val.txt  nvs_test.txt  sem_test.txt` these 4 files and no file is for semantic tain and val.

![image](https://github.com/scannetpp/scannetpp/assets/35106336/a96388a1-424c-4321-9794-47a548dbe593)

I downloaded the dataset several months ago (but after 23 Nov), may I ask whether my files are incomplete?

I will try you mentioned for test set.

**Comment by cy94** [comment]
Please see the documentation https://kaldir.vc.in.tum.de/scannetpp/documentation
`nvs_sem_train` is the train set for both semantic and NVS

**Comment by RayYoh** [comment]
> Specifically you have to remove the transforms `get_labels_on_vertices` and `map_label_to_index` [here](https://github.com/scannetpp/scannetpp/blob/34a10a66503c77cb924db4ef618993d6ffe0d9c0/semantic/configs/prepare_training_data.yml.template#L26) for the test set because labels are not provided. Could you try this out?

Hi. In addition to remove transform, the code in this file [here](https://github.com/scannetpp/scannetpp/blob/34a10a66503c77cb924db4ef618993d6ffe0d9c0/semantic/datasets/scannetpp_release.py#L37) about anno and segment should also be removed.
