### ISSUE TITLE
About the code to process test set

### ISSUE THREAD

**Issue by peoplelu** [scannetpp/scannetpp#74]
Could you provide the code to process test set？There is only the code about train and val set

**Comment by cy94** [comment]
Hi, the same one can be used for test set. You can see this issue https://github.com/scannetpp/scannetpp/issues/71

**Comment by peoplelu** [comment]
> Hi, the same one can be used for test set semantics. You can see this issue #71

Thanks, I understand how to do it.

**Comment by peoplelu** [comment]
> Hi, the same one can be used for test set semantics. You can see this issue #71

Extra question about **3d instance segmentation benchmark**.  Which one should I use about the id: in metadata/semantic_benchmark/top100_instance.txt or in metadata/semantic_benchmark/top100.txt? The id of the same class is different in the two txt.

**Comment by cy94** [comment]
Hi,


_instance.txt is the subset of semantic classes that should be used for the instance benchmark. Please see the data preparation code on how to prepare the data for this


Best,

Chandan

________________________________
