### ISSUE TITLE
Confusion about benchmark label number

### ISSUE THREAD

**Issue by HaoyiZhu** [scannetpp/scannetpp#75]
Hi, thanks for the wonderful project.

For the semantic segmentation benchmark, the benchmark page says it is based on top 100 label classes. However, after I run `python -m semantic.prep.prepare_training_data semantic/configs/prepare_training_data.yml` using the `map_benchmark.csv`, there still exists 1.6k+ label classes:
![image](https://github.com/scannetpp/scannetpp/assets/63538191/7b615b56-5b18-4563-a7a5-9f4197a8b0dc)
So I'm confused. How many classes should my model output?

**Comment by cy94** [comment]
Hi, the `labels_path` list is the one that gets used finally. The script first maps from raw labels to the ones in `map_benchmark` using the mapping in that file. Then it keeps only the ones specified in `labels_path`. Your `labels_path` should point to `semantic_classes.txt` in the metadata folder

**Comment by cy94** [comment]
I'll update the documentation to make it more clear

**Comment by cy94** [comment]
Yes sorry, thats the one

**Comment by kylekam** [comment]
Hi, I'm a little confused about the mapping from the label in "mesh_aligned_0.05_semantic.ply" to the actual class of that point. The description says `The vertex “label” property contains the integer semantic label into the classes in semantic_classes.txt`, but I'm not sure how this relates to "map_benchmark.csv". 

Right now, I'm assuming that I can use this label ID to directly index the corresponding line number in "top100.txt". If the label ID is over 99 or equal to -100 then I just toss it out.

**Comment by cy94** [comment]
Hi @kylekam, the labels in the PLY are the raw labels corresponding to `semantic_classes.txt`. For training and submitting on the benchmark, you should use the provided code along with `map_benchmark.csv` to map these classes to a smaller set of classes. In the resulting files, the top 100 classes will correspond to `top100.txt`

**Comment by kylekam** [comment]
The directions for 3D Semantic Segmentation Evaluation state that we must create `one file per scene named <scene_id>.txt, where each line contains the label(s) for the corresponding vertex in the mesh.` and in `semantic/configs/prepare_training_data.yml` there's a flag for setting max_gt per point. Do the files named "mesh_aligned_0.05_semantic.ply" contain more than one label per point?

**Comment by cy94** [comment]
No, the ply contains only 1 label since it can show only 1 color per vertex for visualization. When you prepare the training/evaluation data you have an option of getting multiple GT per vertex due to multilabeling (see our paper). If you disable multilabel then you get the label of the smallest possible object on each vertex.
