### ISSUE TITLE
Inquiry Regarding Release of Training Code and Model Files for Baseline Method

### ISSUE THREAD

**Issue by adsf0427** [scannetpp/scannetpp#76]
I wanted to inquire if there are any plans to release the training code and model files associated with this baseline method. Having access to these resources would greatly facilitate a deeper understanding and application of your work.

**Comment by cy94** [comment]
Hi,

Thanks for your interest. Could you let us know which baselines you are particularly interested in? We can try to help with that

**Comment by adsf0427** [comment]
Thanks for your response! I'm keen on PointNet++ for semantic segmentation. Could you share the training code, model files, and any setup guidelines? These would greatly speed up my project setup. I really appreciate any help you can provide.

**Comment by cy94** [comment]
Hi @adsf0427 I haven't cleaned up the code yet, but its based on this - https://github.com/daveredrum/Pointnet2.ScanNet which is hopefully a good starting point
