### ISSUE TITLE
Missing sample_labels in split_pth_data for test set

### ISSUE THREAD

**Issue by ThirgoodC** [scannetpp/scannetpp#80]
Hello, I want to use both the iPhone and DSLR data semantic/instance data.
I have undistorted the DSLR, rendered the depth for the iPhone and DSLR, and prepared the iPhone data.

For the test data, using the `prepare_training_data.py`, for the config file I had to change the transforms to be only `add_mesh_vertices` and `sample_points_on_mesh` as indicated by others in the issues for this git repo. In the `ScannetPP_Release_Dataset.py` file I needed to change some of the class in the init and getitem to ignore anno_path and segs_path variables. Otherwise, this was fine for the train and validation sets without the changes.

However, I have then moved onto split_pth_data.py for the same test data set after the process above, and there is no 'sampled_labels' key for any of the test set? Here are the keys read from pth_data (line  85) `dict_keys(['scene_id', 'sampled_coords', 'sampled_colors'])`. Have I missed or broken something with the changes I made in the previous step?
Any help would be appreciated on this.

Also for prepare_semantic_gt.py (after running viz_pth_data) with the train and validation split pth file directories, there are no vtx_labels because in `Prepare 3D semantics Training data` we are told to change these to samples instead of vertices and voxels. Do we need to change them back for this step?

**Comment by ThirgoodC** [comment]
Thank you for the quick response.
I have tried to make some more progress today and found more issues.
Are the masks from the anon DSLR and the iPhone images supposed to be decoded in some way to provide semantic information about the scene or are they used to provide valid depth renderings? If they can be de-anonymized for the semantic information, how can I go about doing this ?

Also When I run the rasterize_semantics_2d.py script, I had to change this line:
`intrinsic_mat = camera_to_intrinsic(colmap_camera)`
to this:
`intrinsic_mat = colmap_camera.K`
Following an issue on another issue. 
Another issue with this script is on line 71 where I get this error:
`  File "/scannetpp/semantic/prep/rasterize_semantics_2d.py", line 76, in <dictcomp>
    all_extrinsics_dict = {v.name: v.to_transform_mat() for v in all_extrinsics.values()}
AttributeError: 'Image' object has no attribute 'to_transform_mat' `

Have I entered the wrong configuration or is there a way to solve this in the code?

**Comment by cy94** [comment]
Hello Christopher,


Reg the masks, please see the official docs: https://kaldir.vc.in.tum.de/scannetpp/documentation

They indicate the vertices/pixels which contain sensitive information and hence have been anonymized. These will be excluded for evaluation


Reg the missing functions, I had forgotten to add the semantics.utils.colmap_utils file. Its there now, its a slightly modified version of the original one. Hopefully that helps, I haven't been able to test it properly.


Best,

Chandan

________________________________

**Comment by ThirgoodC** [comment]
Thank you for the help again!

I am still confused about how to Reg the masks to generate 2d semantic images. How can I do this? or will there be a script that gives the ground truth semantic labels images for all the dslr/iphone images in the future? With scannet200 this data looks to be provided alongside the dataset. I've realised now that the anon masks only give information about bad pixels but I'm still hoping there is a way to get the semantic label images.
 
Also, the colmap_utils file has helped a lot. But I got this error with  rasterize_semantics_2d.py:
`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scannetpp/semantic/prep/rasterize_semantics_2d.py", line 244, in <module>
    main(args)
  File "/scannetpp/semantic/prep/rasterize_semantics_2d.py", line 205, in main
    bbox_min = np.min(nonzero_inds, axis=1)
  File "<__array_function__ internals>", line 200, in amin
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity `

This was my workaround for this:
`
if nonzero_inds[0].size > 0:
    bbox_min = np.min(nonzero_inds, axis=1)
    bbox_max = np.max(nonzero_inds, axis=1)
    bbox = np.concatenate([bbox_min, bbox_max - bbox_min])
    obj_bboxes_2d[int(obj_id)] = bbox.tolist()
else:
    print(f"No valid pixels found for object ID {obj_id}")
`

**Comment by cy94** [comment]
Yes I think that should be fine. Could you check which scene/instance gives that error?

**Comment by kylekam** [comment]
Is it possible to use rasterize_semantics_2d.py to render 2d segmentations on the iPhone images instead of DSLR?

**Comment by cy94** [comment]
Yes its possible, you have to use the `iphone_colmap_dir` to read the iPhone poses, and use the pinhole camera model instead of fisheye
