### ISSUE TITLE
will demos in paper release ?

### ISSUE THREAD

**Issue by BINOFL** [scannetpp/scannetpp#86]
Thank for your great work, I'm wondering if you could release some experiment demo codes presented in the paper? such as do point segmentation/instance segmentation in scannet++ dataset?

**Comment by cy94** [comment]
Hi, Unfortunately the code isn't in a state to release as we never got a chance to clean it up, but you can use these excellent repos to replicate some baselines
Pointcept - Has direct ScanNet++ support https://github.com/Pointcept/Pointcept with many semantic methods and 1 instance method
Minsu3D - has ScanNet support and 3 instance segmentation baselines https://github.com/3dlg-hcvc/minsu3d
PointNet - has ScanNet support https://github.com/daveredrum/Pointnet2.ScanNet
