### ISSUE TITLE
The preparation steps of Semantic Instance Segmentation validation data.

### ISSUE THREAD

**Issue by RongkunYang** [scannetpp/scannetpp#92]
Hello, dear authors?
For the preparation of semantic validation data, do we need to split the complete scene into chunks?
In the process of Readme.md, it is mentioned for validation, the overlap between chunks should be 0.
And I read the code, in the "split_pth_data_train.yml", we need to set both "chunk_dims_xy" and "chunk_stride_xy"  to [5, 5] to achieve this?

**Comment by cy94** [comment]
Chunk splitting is not necessary, its an extra step that can help when the full scene doesn't fit into GPU memory

**Comment by RongkunYang** [comment]
OK, I will try it, and I would like to know whether the baseline code for SoftGroup as baseline can be shared?

**Comment by cy94** [comment]
The results in the leaderboard are based on https://github.com/3dlg-hcvc/minsu3d
I will try to publish the code soon :)

**Comment by RongkunYang** [comment]
Wow, thank you very much, this helps me a lot.

Best wishes!
