### ISSUE TITLE
Question about Rasterize 3D Semantics onto 2D Images

### ISSUE THREAD

**Issue by mingqiJ** [scannetpp/scannetpp#93]
Hi, thanks for your great work.

Could you tell me how to get the 2D segmentation annotation of each image? 
I have tried `semantic.prep.rasterize_semantics_2d` with this command:
`python -m semantic.prep.rasterize_semantics_2d semantic/configs/rasterize_semantics_2d.yml`
But it takes error: `KeyError: 'vtx_instance_anno_id'`

The keys in all pth files start with `sampled_`, not `vtx_`. Like `sampled_instance_anno_id`
Could you tell me how to get the pth files with `vtx_` keys?
Otherwise the `semantic.prep.rasterize_semantics_2d` can not work.

**Comment by cy94** [comment]
Hi @mingqiJ the vtx_ properties are just the ones obtained without sampling points. You can turn off the sampling transform to get annotations on the vertices

**Comment by mingqiJ** [comment]
I see. Thank you. I find some scenes don't contain mesh files, is it normal?

**Comment by cy94** [comment]
Yes, NVS test scenes dont have any 3D geometry

**Comment by mingqiJ** [comment]
Thank you. That is very useful.
