### ISSUE TITLE
scene ``0cf2e9402d`` corrupted

### ISSUE THREAD

**Issue by watermelon097** [scannetpp/scannetpp#97]
Hi there,

I have been trying to use the scene ``0cf2e9402d`` but it seems that the undistorted images is not correct.

For instance those two consecutive images they have different shape for that scale on the kitchen counter. 
![DSC00444](https://github.com/user-attachments/assets/5178a0df-824c-4bed-bc8d-b678850fb0c0)
![DSC00445](https://github.com/user-attachments/assets/ff11dcb3-2cb6-4b71-b3f7-02f033516d5f)

**Comment by cy94** [comment]
The distortion is much heavier towards the edges of the image, that is expected
