### ISSUE TITLE
Are there overlapped scenes btw. ScanNet V2 and ScanNet ++

### ISSUE THREAD

**Issue by oyea0801** [scannetpp/scannetpp#98]
Hi, I want to know whether there are overlapped scenes btw. ScanNet V2 and ScanNet ++.
I currently work on a 3D reconstruction project and our pipeline includes model trained on ScanNet ++
so I want to make sure our performance on ScanNet V2 dataset is valid (no learning the scene characteristic).

In the paper "ScanNet++: A High-Fidelity Dataset of 3D Indoor Scenes", I know that there is at least one scene presented
in both ScanNet V2 and ScanNet ++ (see attached image).

I want to know are there more overlapped scenes (scenes presented in both dataset) than the one mentioned in the paper.
And if there are, please indicate the scene_Id of the overlapped scene in both dataset if possible.
Thanks a lot.

![image](https://github.com/user-attachments/assets/4f876ade-ade7-49a0-a825-da9fab172cc5)

**Comment by cy94** [comment]
Hello @oyea0801 . There might be a small number of similar scenes in the datasets, however there won't be any identical scenes for a few reasons - the data captures are done many years apart, and the data characteristics (laser scan vs. depth sensor) in terms of resolution, completeness, geometry accuracy are completely different. Hence practically it shouldn't make any difference, and we also don't have a list of overlapping scenes. If you find any scenes that are identical please let us know.

**Comment by sunbeam-217** [comment]
Hey @oyea0801, have you successfully downloaded the dataset? I've encountered some issues and could use your assistance.

**Comment by oyea0801** [comment]
@sunbeam-217  Sorry, I use dataset like ScanNet ++ via my lab's server (where the dataset has been download by my seniors). So,  basically I didn't download the dataset on my own so I can't help your issue.
